config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'contacts', to: 'home#contacts'
  post 'create_feedback', to: 'home#create_feedback'

  resources :products do
    resources :comments, only: [:create]
  end

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: :add
    delete 'remove/:id', to: 'carts#remove', as: :remove
    delete 'clear', to: 'carts#clear', as: :clear
    get 'checkout', to: 'carts#checkout', as: :checkout
  end

  resources :orders, only: [:new, :create, :show]

  resources :cart_items, only: [:create] do
    member do
      post :increase_quantity
      post :decrease_quantity
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart_items

  def show
    @cart = current_user.cart || current_user.create_cart
    @cart_items = @cart.cart_items.order(:created_at)  # You can also use :id or another field if needed
  end

  def add
    product = Product.find(params[:product_id])
    cart = current_user.cart || current_user.create_cart

    # Add the product to the user's cart
    cart_item = cart.cart_items.find_by(product: product)

    if cart_item
      # Update quantity if the product already exists in the cart
      cart_item.update(quantity: cart_item.quantity + params[:quantity].to_i)
    else
      # Add new item to the cart
      cart.cart_items.create!(product: product, quantity: params[:quantity])
    end

    redirect_to cart_path(cart), notice: 'Product added to cart!'
  end

  def remove
    cart_item = current_user.cart.cart_items.find(params[:id])
    cart_item.destroy
    redirect_to cart_path, notice: "Товар видалено з кошика"
  end

  def clear
    current_user.cart.cart_items.destroy_all
    redirect_to cart_path, notice: "Ваш кошик очищено"
  end

  def checkout
    # Initialize the order here for the checkout view
    @order = Order.new(user: current_user)
  end

  private

  def set_cart_items
    @cart_items = current_user.cart.cart_items
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/checkout.html.erb
<%= content_for(:title, "Make an order") %>

<h1>Checkout</h1>

<% if @cart_items.any? %>
  <div class="checkout-container">
    <table class="cart-table">
      <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <% @cart_items.each do |item| %>
        <tr class="cart-item">
          <td>
            <div class="cart-item-name">
              <%= item.product.name %>
            </div>
          </td>
          <td>
            <div class="quantity-control">
              <span class="quantity-value"><%= item.quantity %></span>
            </div>
          </td>
          <td>
            <div class="cart-item-price">
              <%= item.product.price * item.quantity %>$
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <h2 class="total">
    Total: <%= number_to_currency(@cart_items.sum { |item| item.product.price * item.quantity }) %>
  </h2>


    <%= form_with model: @order, url: orders_path, local: true, class: 'checkout-form' do |f| %>
      <div class="mb-4">
      <%= f.label :name, "Fullname" %>
      <%= f.text_field :name, class: "input #{'invalid' if @order.errors[:name].any?}" %>
      <% if @order.errors[:name].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:name).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: "input #{'invalid' if @order.errors[:email].any?}" %>
      <% if @order.errors[:email].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:email).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :phone, "Phone number" %>
      <%= f.telephone_field :phone, class: "input #{'invalid' if @order.errors[:phone].any?}" %>
      <% if @order.errors[:phone].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:phone).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class: "input #{'invalid' if @order.errors[:address].any?}" %>
      <% if @order.errors[:address].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:address).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :delivery_method, "Delivery method" %>
      <%= f.select :delivery_method, ["Nova Post", "Ukr Post", "Courier"],
                   { prompt: "Select delivery method..." },
                   class: "input #{'invalid' if @order.errors[:delivery_method].any?}" %>
      <% if @order.errors[:delivery_method].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:delivery_method).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :payment_method, "Payment method" %>
      <%= f.select :payment_method, ["Cash", "Credit Card"],
                   { prompt: "Select payment method..." },
                   class: "input #{'invalid' if @order.errors[:payment_method].any?}" %>
      <% if @order.errors[:payment_method].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:payment_method).join(", ") %></div>
      <% end %>
    </div>

      <div class="mb-4">
      <%= f.label :delivery_address, "Delivery address (if differs from default address)" %>
      <%= f.text_field :delivery_address, class: "input #{'invalid' if @order.errors[:delivery_address].any?}" %>
      <% if @order.errors[:delivery_address].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:delivery_address).join(", ") %></div>
      <% end %>
    </div>
      <div class="mb-4">
      <%= f.label :comment, "Comment" %>
      <%= f.text_area :comment, class: "input #{'invalid' if @order.errors[:comment].any?}" %>
      <% if @order.errors[:comment].any? %>
        <div class="error-message"><%= @order.errors.full_messages_for(:comment).join(", ") %></div>
      <% end %>
    </div>
      <div class="flex mb-4" style="gap: 20px">
      <%= f.submit "Order", class: 'button button__primary' %>
      <%= link_to "To cart", cart_path, class: "button button__dark" %>
    </div>

  <% end %>
  </div>

<% else %>
  <p>Your cart is empty. <%= link_to "To cart", products_path %></p>
<% end %>

app/views/carts/show.html.erb
<%= content_for(:title, "Cart") %>

<h1>Cart</h1>

<% if @cart_items.any? %>
  <div class="cart-container">
    <table class="cart-table">
      <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @cart_items.each do |item| %>
        <tr class="cart-item">
          <td>
            <div class="cart-item-name">
              <%= item.product.name %>
            </div>
          </td>
          <td>
            <div class="quantity-control">
              <%= button_to '-', decrease_quantity_cart_item_path(item), method: :post, class: "button button__decrease" %>
              <span class="quantity-value"><%= item.quantity %></span>
              <%= button_to '+', increase_quantity_cart_item_path(item), method: :post, class: "button button__increase" %>
            </div>
          </td>
          <td>
            <div class="cart-item-price">
              <%= item.product.price * item.quantity %>$
            </div>
          </td>
          <td>
            <div class="cart-item-actions">
              <%= button_to 'Delete', remove_cart_path(item), method: :delete, class: "button button__remove" %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="cart-summary">
      <p><strong>Total price: <%= @cart_items.sum { |item| item.product.price * item.quantity } %>$</strong></p>
      <div class="flex" style="justify-content: space-between;">
        <%= link_to "Back to product", "javascript:history.back()", class: "button button__dark" %>
        <div class="cart-buttons">
          <%= button_to 'Clear cart', clear_cart_path, method: :delete, class: "button button__dark" %>
          <%= link_to "Checkout", checkout_cart_path, class: "button button__primary" %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>Your cart is empty</p>
<% end %>