config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'contacts', to: 'home#contacts'
  post 'create_feedback', to: 'home#create_feedback'

  resources :products do
    resources :comments, only: [:create]
  end

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: :add
    delete 'remove/:id', to: 'carts#remove', as: :remove
    delete 'clear', to: 'carts#clear', as: :clear
    get 'checkout', to: 'carts#checkout', as: :checkout
  end

  resources :orders, only: [:new, :create, :show]

  resources :cart_items, only: [:create] do
    member do
      post :increase_quantity
      post :decrease_quantity
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :comments
  has_one_attached :image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @category = params[:category]

    if params[:category].present?
      @products = Product.where(category: params[:category])
    else
      @products = Product.all
    end

    if params[:query].present?
      @products = @products.where("name LIKE ? OR category LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new', status: 422
    end
  end
  
  private def product_params
    params.require(:product).permit(:name, :description, :price, :category, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= content_for(:title, "Products") %>
<%= content_for(:without_default_wrapper, true) %>

<div class="product-page-wrapper">
  <aside>
    <h2 class="mb-4">Browse by</h2>
    <ul>
      <li>
        <%= link_to "All",
                    products_path,
                    class: "filter__link #{'filter__link--active' if params[:category].blank?}" %>
      </li>
      <li>
        <%= link_to "Jackets",
                    products_path(category: 'Jackets'),
                    class: "filter__link #{'filter__link--active' if params[:category] == 'Jackets'}" %>
      </li>
      <li>
        <%= link_to "Leggings",
                    products_path(category: 'Leggings'),
                    class: "filter__link #{'filter__link--active' if params[:category] == 'Leggings'}" %>
      </li>
      <li>
        <%= link_to "Shorts",
                    products_path(category: 'Shorts'),
                    class: "filter__link #{'filter__link--active' if params[:category] == 'Shorts'}" %>
      </li>
    </ul>
  </aside>
  <div style="flex-grow: 1">
    <h1 class="mb-4">
      <%= @category.present? ? @category : "All Categories" %>
    </h1>
    <% if @products.present? %>
    <div class="product-grid">

        <% @products.each do |product| %>
          <a href="<%= product_path(product) %>" class="product-card-link">
            <div class="product-card">
              <%= render 'shared/image_with_placeholder', image: product.image %>
              <h3><%= product.name %></h3>
              <p class="product-card__price"><%= product.price %>$</p>
              <p class="flex align-items-center" style="gap: 6px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 1024 1024">
                  <path fill="currentColor" d="M573 421c-23.1 0-41 17.9-41 40s17.9 40 41 40c21.1 0 39-17.9 39-40s-17.9-40-39-40m-280 0c-23.1 0-41 17.9-41 40s17.9 40 41 40c21.1 0 39-17.9 39-40s-17.9-40-39-40"/>
                  <path fill="currentColor" d="M894 345c-48.1-66-115.3-110.1-189-130v.1c-17.1-19-36.4-36.5-58-52.1c-163.7-119-393.5-82.7-513 81c-96.3 133-92.2 311.9 6 439l.8 132.6c0 3.2.5 6.4 1.5 9.4c5.3 16.9 23.3 26.2 40.1 20.9L309 806c33.5 11.9 68.1 18.7 102.5 20.6l-.5.4c89.1 64.9 205.9 84.4 313 49l127.1 41.4c3.2 1 6.5 1.6 9.9 1.6c17.7 0 32-14.3 32-32V753c88.1-119.6 90.4-284.9 1-408M323 735l-12-5l-99 31l-1-104l-8-9c-84.6-103.2-90.2-251.9-11-361c96.4-132.2 281.2-161.4 413-66c132.2 96.1 161.5 280.6 66 412c-80.1 109.9-223.5 150.5-348 102m505-17l-8 10l1 104l-98-33l-12 5c-56 20.8-115.7 22.5-171 7l-.2-.1C613.7 788.2 680.7 742.2 729 676c76.4-105.3 88.8-237.6 44.4-350.4l.6.4c23 16.5 44.1 37.1 62 62c72.6 99.6 68.5 235.2-8 330"/>
                  <path fill="currentColor" d="M433 421c-23.1 0-41 17.9-41 40s17.9 40 41 40c21.1 0 39-17.9 39-40s-17.9-40-39-40"/>
                </svg>
                <%= pluralize(product.comments.size, 'comment') %>
              </p>
              <p class="product-card__description"><%= product.description %></p>
            </div>
          </a>

        <% end %>
    </div>
      <% else %>
      <div class="not-found">
          <h2>We couldn't find any matches</h2>
          <p>Try different filters or another category.</p>
        <%= button_to 'Clear Filters', url_for(only_path: true), method: :get, class: 'button button__primary' %>        </div>
      <% end %>

  </div>

</div>

app/views/products/new.html.erb
<%= content_for(:title, "Add product") %>

<h2>Add product</h2>

<%= form_with model: @product, local: true, html: { multipart: true } do |form| %>
  <div class="mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'input' %>
  </div>
  <div class="mb-4">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'input' %>
  </div>
  <div class="mb-4">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'input' %>
  </div>
  <div class="mb-4">
    <%= form.label :category %>
    <%= form.select :category, ["Jackets", "Leggings", "Shorts"],
                    { prompt: "Select category..." }, class: 'input' %>
  </div>
  <div class="mb-4">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'input' %>
  </div>

  <%= form.submit "Create Product", class: 'button button__primary' %>
<% end %>

app/views/products/show.html.erb
<%= content_for(:title, "Product " + @product.name) %>

<div class="product-details">
  <div class="first-column">
    <%= render 'shared/image_with_placeholder', image: @product.image %>
    <div class="summary">
      <h1>
        <%= @product.name %>
      </h1>
      <p class="product-details__price">
        <%= @product.price %>$
      </p>
      <%= form_for :cart_item, url: cart_items_path, method: :post do |form| %>

        <%= hidden_field_tag :product_id, @product.id %>
        <div class="flex" style="gap: 20px;">
          <%= number_field_tag :quantity, 1, min: 1, :class => "input" %>
          <%= form.submit "Add to Cart", :class => "button button__primary" %>
        </div>
      <% end %>
    </div>
  </div>

  <p>
    <%= @product.description %>
  </p>

  <h2>Comments</h2>

  <% if @product.comments.any? %>
    <% @product.comments.each do |comment| %>
      <div class="comment">
        <div class="comment-content">
          <div class="username">
            By: <%= comment.user.email %>
          </div>
          <div class="comment-text">
            <%= comment.body %>
          </div>
          <div class="timestamp">
            <%= comment.created_at.strftime("%B %d, %Y") %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="empty-state">
      No comments yet. Be the first to comment!
    </div>
  <% end %>

  <h2>Add comment</h2>

  <%= form_for([@product, @product.comments.build]) do |form| %>
    <div class="mb-3">
      <%= form.text_area :body, class: "input" %>
    </div>
    <div class="mb-4">
      <%= form.submit "Add comment", :class => "button button__primary" %>
    </div>
  <% end %>
</div>